# Generated by Django 5.1 on 2024-08-27 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('plan_description', models.TextField(blank=True, max_length=100, null=True)),
                ('plan_point', models.IntegerField()),
                ('plan_trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_topic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_usrname', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=200)),
                ('age', models.CharField(blank=True, default='', max_length=200)),
                ('weight', models.CharField(blank=True, default='', max_length=200)),
                ('height', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.CharField(blank=True, default='', max_length=400)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('achivement', models.CharField(blank=True, default='', max_length=200)),
                ('personalTrainer', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rnumber', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='none', max_length=100, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_posted', to='main.client')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_tag', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('joined_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('bio', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('achivement', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('time1', models.CharField(blank=True, max_length=200, null=True)),
                ('time2', models.CharField(blank=True, max_length=200, null=True)),
                ('time3', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_content_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('plan_content_tag', models.TextField(blank=True, max_length=5000, null=True)),
                ('plan_content_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plan')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('staff_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('dnumber', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('answer_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_answered', to='main.client')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_posted', to='main.client')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions_resolved', to='main.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('anumber', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField()),
                ('datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, default='Available', max_length=100, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_booked', to='main.client')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_posted', to='main.trainer')),
            ],
        ),
    ]
