# Generated by Django 5.1 on 2024-08-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='achivement',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='achivement',
            new_name='achievement',
        ),
    ]
