# Generated by Django 5.0 on 2024-08-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_achivement_client_achievement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='status',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='status',
            new_name='gender',
        ),
    ]
