# Generated by Django 5.0 on 2024-08-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_status_client_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, default='Choose option', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(blank=True, default='Choose option', max_length=200, null=True),
        ),
    ]
