# Generated by Django 5.1 on 2024-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bmirecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_usrname',
            field=models.CharField(default='Choose option', max_length=10, unique=True),
        ),
    ]
