# Generated by Django 5.1 on 2024-09-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_owner_owner_usrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_usrname',
            field=models.CharField(default='head', max_length=10, unique=True),
        ),
    ]
