# Generated by Django 5.1.1 on 2024-09-13 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_client_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='wPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wplan_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('wplan_name', models.CharField(max_length=100, unique=True)),
                ('wplan_description', models.TextField(blank=True, max_length=100, null=True)),
                ('wplan_point', models.IntegerField()),
                ('wplan_trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('wplan_topic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wPlan_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wplan_content_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('wplan_content_tag', models.TextField(blank=True, max_length=5000, null=True)),
                ('wplan_content_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('wcontent_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('wdatetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('wplan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plan')),
                ('wupload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
        ),
    ]
