# Generated by Django 5.1.1 on 2024-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_wplan_wplan_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='wplan',
            name='wplan_image',
            field=models.ImageField(blank=True, null=True, upload_to='wplans/'),
        ),
        migrations.AlterField(
            model_name='wplan',
            name='wplan_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
