# Generated by Django 5.1.1 on 2024-09-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_wplan_wplan_image_alter_wplan_wplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wplan_content',
            name='wplan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wplan'),
        ),
    ]
