# Generated by Django 5.1.1 on 2024-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_wplan_content_wplan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wplan_content',
            name='wcontent_count',
            field=models.ImageField(blank=True, null=True, upload_to='countdown/'),
        ),
    ]
